안녕하세요. XGBoost Regressor 와 간단한 feature selection 을 이용한 코드입니다. 상세 설명은 코드의 주석을 참고 바랍니다. 혹시 질문이나 잘못된 부분에 대해 덧글 부탁드립니다. 감사합니다.

# 1. 구현 환경

# 2. 패키지

In [1]:
import os
# os.environ['CUDA_VISIBLE_DEVICES'] = '1' # 사용하려는 GPU 번호
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import train_test_split
import IPython.display as ipd
%matplotlib inline

# 3. 상수 설정

Standardizatino 과 min-max scaling 모두 적용해보았으나 아무것도 적용하지 않은 경우 점수가 더 높았습니다.

In [2]:
SCALE = False

# 4. 데이터 불러오기

In [3]:
trainset = pd.read_csv('train.csv')

In [4]:
# 결측치 확인
np.sum(trainset.isna())

date_time                    0
wind_direction               0
sky_condition                0
precipitation_form           0
wind_speed                   0
humidity                     0
low_temp                     0
high_temp                    0
Precipitation_Probability    0
number_of_rentals            0
dtype: int64

In [5]:
testset = pd.read_csv('test.csv')

In [6]:
# 결측치 확인
np.sum(testset.isna())

date_time                    0
wind_direction               0
sky_condition                0
precipitation_form           0
wind_speed                   0
humidity                     0
low_temp                     0
high_temp                    0
Precipitation_Probability    0
dtype: int64

In [7]:
# 최종 제출을 위한 dataframe 불러오기
submission = pd.read_csv('sample_submission.csv')

원본 dataframe 의 date_time 칼럼은 기계학습 알고리즘에 그대로 적용하기에 정보가 부족합니다. 그래서 정보를 상세하게 풀어서 추가해주었습니다. 
* week: 연도 별로 몇째 주 마다 이용자가 다를 수 있으므로 요일 정보를 추가해줍니다.
* weekday: 요일별로 따릉이 이용자가 다를 수 있으므로 요일 정보를 추가해줍니다.
* <b>추가 해볼 수 있는 것: 평일 / 주말 이용자가 다를 수 있으므로 평일과 주말에 대한 칼럼도 추가해주면 성능 향상에 도움이 될 듯 합니다.</b>

In [10]:
testset['Holiday'] = 0


trainset.loc[trainset["date_time"] == "2018-05-05", "Holiday"] = 1
trainset.loc[trainset["date_time"] == "2018-05-05", "Holiday"] = 1
trainset.loc[trainset["date_time"] == "2018-05-07", "Holiday"] = 1
trainset.loc[trainset["date_time"] == "2018-05-22", "Holiday"] = 1
trainset.loc[trainset["date_time"] == "2018-06-06", "Holiday"] = 1
trainset.loc[trainset["date_time"] == "2018-06-13", "Holiday"] = 1

trainset.loc[trainset["date_time"] == "2019-05-05", "Holiday"] = 1
trainset.loc[trainset["date_time"] == "2019-05-06", "Holiday"] = 1
trainset.loc[trainset["date_time"] == "2019-05-12", "Holiday"] = 1
trainset.loc[trainset["date_time"] == "2019-06-06", "Holiday"] = 1

trainset.loc[trainset["date_time"] == "2020-04-15", "Holiday"] = 1
trainset.loc[trainset["date_time"] == "2020-04-30", "Holiday"] = 1
trainset.loc[trainset["date_time"] == "2020-05-05", "Holiday"] = 1
trainset.loc[trainset["date_time"] == "2020-06-06", "Holiday"] = 1



testset.loc[testset["date_time"] == "2021-05-05", "Holiday"] = 1
testset.loc[testset["date_time"] == "2021-05-19", "Holiday"] = 1
testset.loc[testset["date_time"] == "2021-06-06", "Holiday"] = 1

testset.head(60)

,date_time,wind_direction,sky_condition,precipitation_form,wind_speed,humidity,low_temp,high_temp,Precipitation_Probability,Holiday
0,2021-04-01,108.833,3.000,0.000,2.900,28.333,11.800,20.667,18.333,0
1,2021-04-02,116.717,3.850,0.000,2.662,46.417,12.000,19.000,28.500,0
2,2021-04-03,82.669,4.000,0.565,2.165,77.258,8.875,16.368,52.847,0
3,2021-04-04,44.123,3.466,0.466,3.747,63.288,6.250,17.368,37.671,0
4,2021-04-05,147.791,1.500,0.000,1.560,48.176,7.188,18.684,4.459,0
5,2021-04-06,248.297,2.655,0.000,1.780,55.574,7.250,19.053,17.095,0
6,2021-04-07,266.865,1.000,0.000,1.979,54.696,5.625,17.947,0.000,0
7,2021-04-08,283.142,1.000,0.000,2.570,48.378,6.312,17.632,0.000,0
8,2021-04-09,170.541,1.014,0.000,1.159,44.662,7.250,18.579,0.068,0
9,2021-04-10,202.155,1.351,0.000,2.155,50.811,8.562,19.474,2.432,0
10,2021-04-11,134.243,1.568,0.000,1.366,53.784,11.312,18.105,5.541,0
11,2021-04-12,135.899,3.682,0.419,2.868,59.865,9.625,16.000,40.385,0
12,2021-04-13,272.101,2.709,0.358,3.518,64.291,5.500,15.316,29.865,0
13,2021-04-14,274.912,1.000,0.000,2.514,49.155,6.188,15.947,0.000,0
14,2021-04-15,196.209,1.257,0.000,1.570,56.959,7.938,16.421,2.365,0
15,2021-04-16,192.946,2.385,0.372,3.351,57.297,6.562,15.737,25.270,0
16,2021-04-17,217.818,2.115,0.541,2.757,55.709,6.250,17.000,17.297,0
17,2021-04-18,281.486,1.297,0.000,3.109,57.466,7.312,19.211,5.608,0
18,2021-04-19,215.399,1.000,0.000,2.285,59.527,9.125,22.158,0.000,0
19,2021-04-20,213.000,1.662,0.000,1.591,59.493,11.875,25.789,7.095,0
20,2021-04-21,177.277,1.730,0.000,1.224,51.824,14.750,25.842,6.149,0
21,2021-04-22,187.993,3.149,0.000,1.847,46.689,14.812,24.053,22.568,0
22,2021-04-23,96.851,3.919,0.034,2.486,46.858,13.562,23.263,30.203,0
23,2021-04-24,165.189,3.480,0.000,1.624,43.581,12.375,23.105,23.784,0
24,2021-04-25,130.574,1.000,0.000,2.227,47.534,10.812,21.895,0.541,0
25,2021-04-26,181.453,1.811,0.000,1.804,39.054,11.625,20.474,7.905,0
26,2021-04-27,191.108,3.588,0.027,1.645,54.459,11.500,20.053,26.959,0
27,2021-04-28,231.257,2.182,0.223,2.366,59.527,11.500,20.105,20.811,0
28,2021-04-29,175.993,3.095,0.000,1.526,48.277,10.625,17.947,20.405,0
29,2021-04-30,216.838,3.601,0.304,2.722,68.412,9.500,16.105,36.122,0
30,2021-05-01,313.167,4.000,1.000,2.767,79.167,8.400,18.500,60.000,0
31,2021-05-02,278.317,1.983,0.150,1.827,64.167,9.625,19.895,14.667,0
32,2021-05-03,231.839,1.194,0.000,1.873,55.121,11.625,19.947,2.742,0
33,2021-05-04,172.630,3.781,0.541,2.454,75.411,11.188,19.316,44.370,0
34,2021-05-05,252.946,1.730,0.230,3.341,65.203,10.688,20.316,15.730,1
35,2021-05-06,189.108,1.095,0.000,2.490,45.743,12.000,20.632,1.351,0
36,2021-05-07,204.277,1.831,0.203,4.871,54.459,11.250,20.316,14.595,0
37,2021-05-08,207.730,1.635,0.000,4.314,60.304,10.000,20.316,6.351,0
38,2021-05-09,266.034,1.000,0.000,3.507,55.777,11.625,20.737,0.000,0
39,2021-05-10,158.561,3.426,0.216,1.249,71.115,12.188,22.211,30.608,0
40,2021-05-11,98.142,1.189,0.000,2.116,52.264,14.750,27.263,2.162,0
41,2021-05-12,111.291,2.291,0.000,2.380,45.811,16.875,28.368,13.176,0
42,2021-05-13,191.155,1.243,0.000,1.382,58.784,17.812,28.421,2.162,0
43,2021-05-14,165.176,1.122,0.000,1.097,60.034,19.312,26.105,1.216,0
44,2021-05-15,121.561,3.527,0.230,1.805,73.074,18.062,22.000,32.703,0
45,2021-05-16,76.541,4.000,0.669,1.831,85.372,15.938,21.105,55.946,0
46,2021-05-17,67.824,3.838,0.277,1.857,78.007,14.562,23.737,37.770,0
47,2021-05-18,189.878,1.878,0.000,1.384,66.824,15.000,26.158,9.797,0
48,2021-05-19,239.534,1.000,0.000,1.353,54.493,15.688,24.368,0.000,1
49,2021-05-20,73.149,3.291,0.216,2.491,62.534,15.062,22.632,29.662,0
50,2021-05-21,186.216,3.946,0.439,2.386,77.264,14.250,23.579,43.108,0
51,2021-05-22,241.926,1.757,0.000,2.024,70.608,14.812,24.789,7.365,0
52,2021-05-23,222.304,2.196,0.000,1.703,65.439,15.062,23.632,11.959,0
53,2021-05-24,233.162,2.331,0.000,2.068,63.750,13.312,22.474,13.311,0
54,2021-05-25,229.973,2.318,0.318,2.602,68.378,12.688,22.000,24.054,0
55,2021-05-26,183.473,1.730,0.047,2.402,59.696,14.188,21.737,10.068,0
56,2021-05-27,205.385,3.250,0.264,2.448,76.081,14.188,21.263,30.865,0
57,2021-05-28,197.365,3.338,0.291,3.309,78.311,14.000,22.526,36.405,0
58,2021-05-29,253.182,2.730,0.054,2.312,71.791,15.000,24.368,19.324,0
59,2021-05-30,150.635,2.074,0.088,1.745,62.162,16.375,25.368,13.446,0

In [11]:
trainset['Temperature']= (trainset['low_temp']+trainset['high_temp'])/2
testset['Temperature']= (testset['low_temp']+testset['high_temp'])/2
trainset['Feeling'] = (5/9)*trainset['Temperature']-0.55*((100-trainset['humidity'])/100)*((5/9)*trainset['Temperature']-26)+32
testset['Feeling'] = (5/9)*testset['Temperature']-0.55*((100-testset['humidity'])/100)*((5/9)*testset['Temperature']-26)+32

In [12]:
def split_date(df):
    '''
    args
        df: 원본 데이터프레임
    return
        year, month, day, week, weekday 정보를 추가한 dataframe
    '''
    df['year'] = pd.to_datetime(df['date_time']).dt.year
    df['month'] = pd.to_datetime(df['date_time']).dt.month
    df['day'] = pd.to_datetime(df['date_time']).dt.day
    df['week'] = pd.to_datetime(df['date_time']).dt.week
    df['weekday'] = pd.to_datetime(df['date_time']).dt.weekday
    # df['quarter'] = pd.to_datetime(df['date_time']).dt.quarter # 데이터는 모두 동일 분기 데이터이므로 무의미
    
    return df.drop(columns=['date_time'])

In [13]:
traindf = split_date(trainset)
testdf = split_date(testset)

In [14]:
keys = traindf.drop(columns=['number_of_rentals']).keys()

In [15]:
traindf.head()

,wind_direction,sky_condition,precipitation_form,wind_speed,humidity,low_temp,high_temp,Precipitation_Probability,number_of_rentals,Holiday,Temperature,Feeling,year,month,day,week,weekday
0,207.500,4.000,0.000,3.050,75.000,12.600,21.000,30.000,22994,NaN,16.800,43.625000,2018,4,1,13,6
1,208.317,2.950,0.000,3.278,69.833,12.812,19.000,19.500,28139,NaN,15.906,43.684381,2018,4,2,14,0
2,213.516,2.911,0.000,2.690,74.879,10.312,15.316,19.113,26817,NaN,12.814,41.727607,2018,4,3,14,1
3,143.836,3.692,0.425,3.138,71.849,8.312,12.368,43.493,26034,NaN,10.340,40.880622,2018,4,4,14,2
4,95.905,4.000,0.723,3.186,73.784,5.875,10.421,63.378,2833,NaN,8.148,39.622864,2018,4,5,14,3

In [16]:
testdf.head()

,wind_direction,sky_condition,precipitation_form,wind_speed,humidity,low_temp,high_temp,Precipitation_Probability,Holiday,Temperature,Feeling,year,month,day,week,weekday
0,108.833,3.000,0.000,2.900,28.333,11.800,20.667,18.333,0,16.2335,47.712140,2021,4,1,13,3
1,116.717,3.850,0.000,2.662,46.417,12.000,19.000,28.500,0,15.5000,45.735730,2021,4,2,13,4
2,82.669,4.000,0.565,2.165,77.258,8.875,16.368,52.847,0,12.6215,41.386989,2021,4,3,13,5
3,44.123,3.466,0.466,3.747,63.288,6.250,17.368,37.671,0,11.8090,42.485690,2021,4,4,13,6
4,147.791,1.500,0.000,1.560,48.176,7.188,18.684,4.459,0,12.9360,44.549069,2021,4,5,14,0

In [17]:
keydict = dict()
for i, k in enumerate(keys):
    keydict[i]=k

데이터 학습을 위해 입력값과 출력값을 분리해줍니다.

In [18]:
X = np.array(traindf.drop(columns=['number_of_rentals'])).astype(float)
y = np.array(traindf['number_of_rentals']).astype(float)
X_test = np.array(testdf).astype(float)

if SCALE:
    x_max = np.max(X, 0)
    y_max = np.max(y, 0)
    X /= x_max
    y /= y_max
    X_test /= x_max

# 5. 유틸리티

In [19]:
def nmae(true, pred):
    return np.mean(np.abs(true-pred)/true)

성능 확인을 위해서 몬테카를로 교차검증을 사용합니다([링크](https://en.wikipedia.org/wiki/Cross-validation_(statistics)의 섹션 Repeated random sub-sampling validation 참고).

In [20]:
def cv(model, X=X, y=y, cnt=100, test_size=.5):
    score = list()
    seeds = np.random.choice(np.arange(1e5), size=cnt, replace=False)
    for seed in seeds:
        X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=test_size)
        model.fit(X_train, y_train)
        y_pred = model.predict(X_valid)
        if SCALE:
            y_pred *= y_max
            y_valid *= y_max
        score.append(nmae(y_valid, y_pred))
    return np.mean(score)

# 6. Feature selection

제거 법을 이용해서 feature selection 을 해봅니다.

In [21]:
def select_features(X, cols):
    _X = list()
    for c in cols:
        _X.append(np.expand_dims(X[:, c],-1))
    return np.concatenate(_X, axis=1)

In [22]:
keydict

{0: 'wind_direction',
 1: 'sky_condition',
 2: 'precipitation_form',
 3: 'wind_speed',
 4: 'humidity',
 5: 'low_temp',
 6: 'high_temp',
 7: 'Precipitation_Probability',
 8: 'Holiday',
 9: 'Temperature',
 10: 'Feeling',
 11: 'year',
 12: 'month',
 13: 'day',
 14: 'week',
 15: 'weekday'}

다양한 모델 확인 결과 XGBRegressor 가 가장 좋아서 이걸 선택했습니다.

In [23]:
from xgboost import XGBRegressor as Model

In [24]:
min_loss = 1e10
min_cols = None

for i in np.arange(start=0, stop=len(keys)):
#     model = Model(tree_method='gpu_hist')
#     model = Model(silent = 1)
    model = Model(eta = 0.1)
    cols = np.arange(len(keys))
    cols = np.delete(cols, i)
    _X = select_features(X, cols)
    loss = cv(model, _X, y, cnt=30)
    if min_loss > loss:
        min_loss = loss
        min_cols = f"{keydict.get(i)}"
    print(f"{keydict.get(i)}, {loss:.4f} (min {min_loss:.4f})")

wind_direction, 0.2485 (min 0.2485)
sky_condition, 0.2431 (min 0.2431)
precipitation_form, 0.2531 (min 0.2431)
wind_speed, 0.2395 (min 0.2395)
humidity, 0.2419 (min 0.2395)
low_temp, 0.2530 (min 0.2395)
high_temp, 0.2610 (min 0.2395)
Precipitation_Probability, 0.2545 (min 0.2395)
Holiday, 0.2385 (min 0.2385)
Temperature, 0.2429 (min 0.2385)
Feeling, 0.2381 (min 0.2381)
year, 0.4591 (min 0.2381)
month, 0.2571 (min 0.2381)
day, 0.2437 (min 0.2381)
week, 0.2526 (min 0.2381)
weekday, 0.2266 (min 0.2266)

In [25]:
for i in np.arange(start=0, stop=len(keys)-1):
    for j in np.arange(start=i+1, stop=len(keys)):
#         model = Model(tree_method='gpu_hist')
        model = Model(eta = 0.1)
        cols = np.arange(len(keys))
        cols = np.delete(cols, [i,j])
        _X = select_features(X, cols)
        loss = cv(model, _X, y, cnt=30)
        if min_loss > loss:
            min_loss = loss
            min_cols = f"{keydict.get(i)}, {keydict.get(j)}"
        print(f"{keydict.get(i)}, {keydict.get(j)}, {loss:.4f} (min {min_loss:.4f})")

wind_direction, sky_condition, 0.2495 (min 0.2266)
wind_direction, precipitation_form, 0.2506 (min 0.2266)
wind_direction, wind_speed, 0.2454 (min 0.2266)
wind_direction, humidity, 0.2450 (min 0.2266)
wind_direction, low_temp, 0.2521 (min 0.2266)
wind_direction, high_temp, 0.2672 (min 0.2266)
wind_direction, Precipitation_Probability, 0.2501 (min 0.2266)
wind_direction, Holiday, 0.2603 (min 0.2266)
wind_direction, Temperature, 0.2353 (min 0.2266)
wind_direction, Feeling, 0.2315 (min 0.2266)
wind_direction, year, 0.4448 (min 0.2266)
wind_direction, month, 0.2510 (min 0.2266)
wind_direction, day, 0.2442 (min 0.2266)
wind_direction, week, 0.2301 (min 0.2266)
wind_direction, weekday, 0.2447 (min 0.2266)
sky_condition, precipitation_form, 0.2597 (min 0.2266)
sky_condition, wind_speed, 0.2229 (min 0.2229)
sky_condition, humidity, 0.2387 (min 0.2229)
sky_condition, low_temp, 0.2561 (min 0.2229)
sky_condition, high_temp, 0.2423 (min 0.2229)
sky_condition, Precipitation_Probability, 0.2464 (min 0.2229)
sky_condition, Holiday, 0.2605 (min 0.2229)
sky_condition, Temperature, 0.2338 (min 0.2229)
sky_condition, Feeling, 0.2607 (min 0.2229)
sky_condition, year, 0.4871 (min 0.2229)
sky_condition, month, 0.2304 (min 0.2229)
sky_condition, day, 0.2645 (min 0.2229)
sky_condition, week, 0.2498 (min 0.2229)
sky_condition, weekday, 0.2479 (min 0.2229)
precipitation_form, wind_speed, 0.2707 (min 0.2229)
precipitation_form, humidity, 0.2690 (min 0.2229)
precipitation_form, low_temp, 0.2401 (min 0.2229)
precipitation_form, high_temp, 0.2509 (min 0.2229)
precipitation_form, Precipitation_Probability, 0.2975 (min 0.2229)
precipitation_form, Holiday, 0.2332 (min 0.2229)
precipitation_form, Temperature, 0.2394 (min 0.2229)
precipitation_form, Feeling, 0.2455 (min 0.2229)
precipitation_form, year, 0.4893 (min 0.2229)
precipitation_form, month, 0.2550 (min 0.2229)
precipitation_form, day, 0.2354 (min 0.2229)
precipitation_form, week, 0.2538 (min 0.2229)
precipitation_form, weekday, 0.2603 (min 0.2229)
wind_speed, humidity, 0.2442 (min 0.2229)
wind_speed, low_temp, 0.2489 (min 0.2229)
wind_speed, high_temp, 0.2583 (min 0.2229)
wind_speed, Precipitation_Probability, 0.2445 (min 0.2229)
wind_speed, Holiday, 0.2349 (min 0.2229)
wind_speed, Temperature, 0.2478 (min 0.2229)
wind_speed, Feeling, 0.2285 (min 0.2229)
wind_speed, year, 0.5631 (min 0.2229)
wind_speed, month, 0.2432 (min 0.2229)
wind_speed, day, 0.2341 (min 0.2229)
wind_speed, week, 0.2369 (min 0.2229)
wind_speed, weekday, 0.2432 (min 0.2229)
humidity, low_temp, 0.2310 (min 0.2229)
humidity, high_temp, 0.2473 (min 0.2229)
humidity, Precipitation_Probability, 0.2367 (min 0.2229)
humidity, Holiday, 0.2377 (min 0.2229)
humidity, Temperature, 0.2340 (min 0.2229)
humidity, Feeling, 0.2238 (min 0.2229)
humidity, year, 0.4541 (min 0.2229)
humidity, month, 0.2497 (min 0.2229)
humidity, day, 0.2620 (min 0.2229)
humidity, week, 0.2410 (min 0.2229)
humidity, weekday, 0.2404 (min 0.2229)
low_temp, high_temp, 0.2348 (min 0.2229)
low_temp, Precipitation_Probability, 0.2524 (min 0.2229)
low_temp, Holiday, 0.2408 (min 0.2229)
low_temp, Temperature, 0.2383 (min 0.2229)
low_temp, Feeling, 0.2515 (min 0.2229)
low_temp, year, 0.4712 (min 0.2229)
low_temp, month, 0.2370 (min 0.2229)
low_temp, day, 0.2483 (min 0.2229)
low_temp, week, 0.2526 (min 0.2229)
low_temp, weekday, 0.2325 (min 0.2229)
high_temp, Precipitation_Probability, 0.2446 (min 0.2229)
high_temp, Holiday, 0.2599 (min 0.2229)
high_temp, Temperature, 0.2471 (min 0.2229)
high_temp, Feeling, 0.2505 (min 0.2229)
high_temp, year, 0.4686 (min 0.2229)
high_temp, month, 0.2446 (min 0.2229)
high_temp, day, 0.2336 (min 0.2229)
high_temp, week, 0.2498 (min 0.2229)
high_temp, weekday, 0.2550 (min 0.2229)
Precipitation_Probability, Holiday, 0.2480 (min 0.2229)
Precipitation_Probability, Temperature, 0.2330 (min 0.2229)
Precipitation_Probability, Feeling, 0.2584 (min 0.2229)
Precipitation_Probability, year, 0.4564 (min 0.2229)
Precipitation_Probability, month, 0.2485 (min 0.2229)
Precipitation_Probability, day, 0.2560 (min 0.2229)
Precipitation_Probability, week, 0.2718 (min 0.2229)
Precipitation_Probability, weekday, 0.2458 (min 0.2229)
Holiday, Temperature, 0.2372 (min 0.2229)
Holiday, Feeling, 0.2471 (min 0.2229)
Holiday, year, 0.4639 (min 0.2229)
Holiday, month, 0.2356 (min 0.2229)
Holiday, day, 0.2385 (min 0.2229)
Holiday, week, 0.2394 (min 0.2229)
Holiday, weekday, 0.2405 (min 0.2229)
Temperature, Feeling, 0.2449 (min 0.2229)
Temperature, year, 0.4911 (min 0.2229)
Temperature, month, 0.2335 (min 0.2229)
Temperature, day, 0.2440 (min 0.2229)
Temperature, week, 0.2369 (min 0.2229)
Temperature, weekday, 0.2472 (min 0.2229)
Feeling, year, 0.4894 (min 0.2229)
Feeling, month, 0.2478 (min 0.2229)
Feeling, day, 0.2373 (min 0.2229)
Feeling, week, 0.2417 (min 0.2229)
Feeling, weekday, 0.2560 (min 0.2229)
year, month, 0.4502 (min 0.2229)
year, day, 0.4684 (min 0.2229)
year, week, 0.5387 (min 0.2229)
year, weekday, 0.4950 (min 0.2229)
month, day, 0.2394 (min 0.2229)
month, week, 0.2388 (min 0.2229)
month, weekday, 0.2354 (min 0.2229)
day, week, 0.2472 (min 0.2229)
day, weekday, 0.2481 (min 0.2229)
week, weekday, 0.2309 (min 0.2229)

0: 'wind_direction' 과  7: 'Precipitation_Probability' 가 없을 때 성능이 좋을듯 합니다. 풍향은 자전거 이용에 영향을 미치는 변수가 아닐 듯 합니다. 한편, 강수확률(Precipitation_Probability)은 관측치가 아니라 기상청 예측치라면, 예측 오류가 우리가 만드는 최종 모델의 오류를 더 커지게 할 수 있기 때문에 빼는 것이 좋겠습니다.

## min_loss = 0.2227

# 7. 모델 학습

In [26]:
model = Model(eta = 0.1)

cols = np.arange(len(keys))
cols = np.delete(cols, [0,7]) # 풍향, 강수확률 제거
_X = select_features(X, cols)

model.fit(_X, y)

_X_test = select_features(X_test, cols)
y_pred = model.predict(_X_test)
if SCALE:
    y_pred *= y_max
y_pred = y_pred.astype(int)

# plt.scatter(np.arange(len(y_pred)), y_pred, s=.5)
# plt.show()

In [27]:
submission['number_of_rentals'] = y_pred

In [28]:
submission.to_csv('0.1-holiday-feeling-hyperparam-copy_xgboost_submission.csv', index=False)

# score =0.4956833938	( eta = 0.1)
# score =0.4987798086	(eta = 0.05)

현재 순위 13등/415